const { Client, LocalAuth } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const mongoose = require("mongoose");
const User = require("./models/user.js");
const chatSession = require('./services/aiModel.js');

mongoose
    .connect("mongodb://localhost:27017/whatsappdb")
    .then(() => console.log("Connected with db"))
    .catch(err => {
        console.error("Database connection failed:", err);
        process.exit(1); 
    });


    const client = new Client({
        authStrategy: new LocalAuth({
            dataPath: 'session',
        }),
    });
    


client.on('qr', (qr) => {
    console.log('QR RECEIVED'); // Ensure this log appears
    qrcode.generate(qr, { small: true });
});



client.on('ready', () => {
    console.log('Client is ready!');
});


client.on('message', async (msg) => {
    const contact = await msg.getContact();

    // Ensure contact details are valid
    const contactName = contact.pushname || "Unknown";
    const contactNumber = contact.number;
    console.log(`${contactName} ---> ${msg.body}`);

    // Fetch user from the database
    const user = await User.findOne({ number: contactNumber });

    if (msg.body.toUpperCase() === 'HI') {
        if (user) {
            user.active = true;
            await user.save();
        } else {
            await User.create({
                name: contactName,
                number: contactNumber,
                active: true,
            });
        }
        console.log(`User ${contactName} is now active.`);
        msg.reply(`Hi ${contactName}`);
    } else if (msg.body.toUpperCase() === 'CLOSE') {
        if (user && user.active) {
            user.active = false;
            await user.save();
            msg.reply("Bye bye sherrrrr!!");
        }
    } else {
        if (user && user.active) {
            // msg.reply(`msg sent by Gemini AI`);
            const AI_PROMPT = `hey gemini i will be using you for replying my whatsapp bot, you will be a boy whose name is Ayush Sikarwal and he is Indian. He is in college called IIT KGP, his nature is very jolly and he is intelligent in studies. Girls trust him so much. He is also a good friend of everyone, always try to settle the issues if happened any. Also he use little bit punjabi slang while talking, so this is about the ayush sikarwal. so u have to be like ayush sikarwal and reply on behalf of him. It should not feel anybody that the replies are being generated by AI. use Hinglish for the reply and also use emojis in reply but not everytime. so this is that messaged u received: ${msg.body}. And remember u have to generate a single reply, not to give many options. suppose you are Ayush Sikarwal so reply like him only. (PS: dont use so much emojis, also use different punjabi slang) Also use lil bit humour and keep reply lil short and use messaging language. Most important keep replies lil short. dont wrap msgs in double inverted commas. dont use "oye hoye" very much`

            const result = await chatSession.sendMessage(AI_PROMPT)

            msg.reply(result.response.text())
        } 
    }
});

// Initialize the client
client.initialize();
